title: Patrick Fong Portfolio
email: patfmeche@gmail.com
description: A portfolio of mechanical engineering projects.
baseurl: ""
url: "https://mangohead12.github.io/patrickfong-portfolio"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-seo-tag
collections:
  projects:
    output: true
    permalink: /projects/:name/
