title: Patrick Fong - Project Portfolio
email: patfmeche@gmail.com
description: >-
  A mechanical engineering project portfolio featuring robotic systems, design for manufacturing, and prototyping.
baseurl: ""
url: "https://mangohead12.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag